[project]
name = "qmtl-project"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["qmtl"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.uv]
package = false

