name: Docs

on:
  pull_request:
    paths:
      - '**/*.md'
      - '.github/workflows/docs.yml'

jobs:
  lint-and-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress './**/*.md'
