#!/usr/bin/env python3
"""Generate consolidated agent instructions from AGENTS.md files."""

from __future__ import annotations

from pathlib import Path
import sys

try:
    import yaml
except Exception as exc:  # pragma: no cover - dependency error
    print(f"PyYAML required: {exc}")
    sys.exit(1)

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_FILE = ROOT / "docs" / "agents-instructions.md"


def parse_agents_file(path: Path) -> tuple[dict, str]:
    """Return front matter and body text from an AGENTS.md file."""
    text = path.read_text()
    if text.startswith("---"):
        parts = text.split("---", 2)
        front = yaml.safe_load(parts[1]) or {}
        body = parts[2].lstrip("\n")
    else:
        front, body = {}, text
    return front, body


def build_instructions() -> str:
    lines: list[str] = [
        "# Agent Instructions",
        "",
        "This file is auto-generated by `scripts/build_agent_instructions.py`.",
        "",
    ]
    for path in sorted(ROOT.rglob("AGENTS.md")):
        front, body = parse_agents_file(path)
        rel = path.relative_to(ROOT).as_posix()
        scope = front.get("scope", "unspecified scope")
        lines.append(f"## {rel} (scope: {scope})")
        lines.append("")
        lines.append(body.strip())
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    OUTPUT_FILE.write_text(build_instructions())
    print(f"Wrote {OUTPUT_FILE}")
    return 0


if __name__ == "__main__":  # pragma: no cover - script entry point
    raise SystemExit(main())
