from typing import Any, Protocol

class Exchange(Protocol):
    def __init__(self, params: dict[str, Any]) -> None: ...

    def create_order(
        self, symbol: str, typ: str, side: str, amount: Any, price: Any, params: dict[str, Any] | None = ...
    ) -> Any: ...

    def fetch_order(self, order_id: Any, symbol: str | None = ...) -> Any: ...

    def cancel_order(self, order_id: str, *args: Any, **kwargs: Any) -> Any: ...

    def set_sandbox_mode(self, enabled: bool) -> Any: ...

    def setSandboxMode(self, enabled: bool) -> Any: ...

    def set_position_mode(self, hedge_mode: bool) -> Any: ...

    def set_margin_mode(self, mode: str, symbol: str) -> Any: ...

    def set_leverage(self, leverage: int, symbol: str) -> Any: ...

def __getattr__(name: str) -> type[Exchange]: ...
